### ISSUE TITLE
Sorting first column does not work if HTML exists in cell

### ISSUE THREAD

**Issue by ianchan** [gyrocode/jquery-datatables-alphabetSearch#2]
Hi,
I've spent a couple hours trying to diagnose the problem with sorting the first column on https://biblio.csusm.edu/course-reserves. It'll only work if the column has no HTML in the cell. If you wouldn't mind taking a look, I'd really appreciate it.

Thank you.

Ian

**Comment by julkue** [comment]
@ianchan I think you're wrong in this repo, this is only about the search functionality of the table. You might better ask in the datatables repo itself

**Comment by mpryvkin** [comment]
@julmot This is indeed problem with this extension. @ianchan please let me think of the possible solution.

**Comment by mpryvkin** [comment]
It has been corrected. Thanks for reporting the issue!

**Comment by ianchan** [comment]
Thank you!
