### ISSUE TITLE
Variable search column?

### ISSUE THREAD

**Issue by barbequesauce** [gyrocode/jquery-datatables-alphabetSearch#3]
As you probably know, the default datatables presentation allows you to sort on any column by clicking on the header one or more times.

How can this module be used with a focus on a dynamically sorted column? Meaning, start with a given column (“2”) but on a user sort move to that column?

**Comment by barbequesauce** [comment]
To expand further - Pier Luigi's issue 2 on the[ comments page ](https://www.gyrocode.com/articles/jquery-datatables-alphabetical-search/comment-page-1/#comment-25089)documents my problem pretty well.

Pier Luigi   February 24, 2017 at 12:20 pm
Some small suggestions:
<snip>
– by clicking the “All” option the data are still grouped by letters and choosing the sort column affect only the grouped rows. In some cases could be very useful to have an extra clickable option (like “Off”) with the effect to activate/deactivate on the fly the alphabet input behavior.

**Comment by mpryvkin** [comment]
AlphabetSearch is a row grouping plug-in. If I allow sorting by any column, row grouping must be deactivated.

You are referencing the comment on the website that requests ability to disable row grouping. Would it work for you if I add ability to disable grouping by adding another option in addition to "All" as Pier Luigi suggested? 

Pier Luigi on the website suggested naming it "Off", but I think it's confusing.

**Comment by barbequesauce** [comment]
Yes, you’re right - the wording is confusing. Some way to disable grouping would cover the need... 

Thanks!

**Comment by mpryvkin** [comment]
I am thinking to add additional option that will enable/disable grouping when "All" is selected instead of adding another selector in addition to "All".

**Comment by barbequesauce** [comment]
Usual datatable sorts have three conditions - ascending, descending, and unsorted.

Maybe All can take two meanings (indicated with onhover): All (grouped) and All (ungrouped)?

**Comment by barbequesauce** [comment]
Alternately, if you add an enable/disable toggle [like RowGroup does](https://datatables.net/reference/api/rowGroup().enable()), I could use that on order.dt events...

**Comment by barbequesauce** [comment]
Hi - any update on this?

**Comment by mpryvkin** [comment]
Sorry, didn't have time to work on this. I will try to dedicate some time this or next week.

**Comment by barbequesauce** [comment]
Gentle reminder...
